import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import therapistRoutes from './routes/therapistRoutes.js';
import publicRoutes from './routes/publicRoutes.js';
import schedulingRoutes,{publicScheduling,bookingRoutes} from './routes/schedulingRoutes.js';
import clientRoutes from './routes/clientRoutes.js';
import authRoutes from './routes/authRoutes.js';
import {errorHandler,notFound} from './middleware/errorHandler.js';
import Therapist from './models/Therapist.js';
import {profileHtml} from './services/profileHtmlService.js';
import {fileURLToPath} from 'node:url';
export const app = express();
app.use(helmet());
app.use(cors({origin: process.env.FRONTEND_URL || 'http://localhost:5173'}));
app.use(express.json({limit:'64kb'}));
app.get('/api/health', (_req,res)=>res.json({status:'ok'}));
app.use('/api/auth',authRoutes);
app.use('/api/therapists',therapistRoutes);
app.use('/api/bookings',bookingRoutes);
app.use('/api/scheduling',schedulingRoutes);
app.use('/api/public',publicScheduling);
app.use('/api/public',publicRoutes);
app.use(express.static(fileURLToPath(new URL('../../unfazed-frontend/dist',import.meta.url))));
app.get('/:slug',async(req,res,next)=>{const therapist=await Therapist.findOne({slug:req.params.slug});if(!therapist)return next();res.type('html').send(await profileHtml(therapist));});
app.get(/^\/(?!api(?:\/|$)).*/,(_req,res)=>res.sendFile(fileURLToPath(new URL('../../unfazed-frontend/dist/index.html',import.meta.url))));
app.use('/api/clients',clientRoutes);
app.use(notFound);
app.use(errorHandler);
